/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_andye_cocrash_NativeCoCrash */

#ifndef _Included_com_andye_cocrash_NativeCoCrash
#define _Included_com_andye_cocrash_NativeCoCrash
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_andye_cocrash_NativeCoCrash
 * Method:    nativeInit
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_andye_cocrash_NativeCoCrash_nativeInit
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_andye_cocrash_NativeCoCrash
 * Method:    nativeTestCrash
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_andye_cocrash_NativeCoCrash_nativeTestCrash
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
